import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import ConditionalLayout from '@/components/ConditionalLayout'
import { Toaster } from 'react-hot-toast'
import ContextProvider from '@/utils/Context'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'SASSAI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <ConditionalLayout>
            {children} <Toaster />
          </ConditionalLayout>
        </ContextProvider>
      </body>
    </html>
  )
}
